# tasks file
---
- name: add group
  ansible.builtin.group:
    name: "{{ item }}"
    system: true
  with_items: "{{ [cacti_client_group] + cacti_client_groups }}"
  tags:
    - configuration
    - cacti-client
    - cacti-client-add-group

- name: add user
  ansible.builtin.user:
    name: "{{ cacti_client_user }}"
    system: true
    group: "{{ cacti_client_group }}"
    groups: "{{ cacti_client_groups | join(',') }}"
  tags:
    - configuration
    - cacti-client
    - cacti-client-add-user

- name: create authorized_keys from public key
  ansible.posix.authorized_key:
    user: "{{ cacti_client_user }}"
    key: "{{ lookup('file', item.src) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ cacti_client_authorized_keys }}"
  tags:
    - configuration
    - cacti-client
    - cacti-client-authorized-keys
