# tasks file for cacti-client
---
- name: add group
  group:
    name: "{{ item }}"
  with_flattened:
    - cacti_client_group
    - cacti_client_groups
  tags:
    - configuration
    - cacti-client
    - cacti-client-add-group

- name: add user
  user:
    name: "{{ cacti_client_user }}"
    group: "{{ cacti_client_group }}"
    groups: "{{ cacti_client_groups | join(',') }}"
  tags:
    - configuration
    - cacti-client
    - cacti-client-add-user

- name: create authorized_keys from public key
  authorized_key:
    user: "{{ cacti_client_user }}"
    key: "{{ lookup('file', item.src) }}"
    state: "{{ item.state | default('present') }}"
  with_items: cacti_client_authorized_keys
  tags:
    - configuration
    - cacti-client
    - cacti-client-authorized-keys
